name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
    - run: sudo apt-get install cmake avrdude avr-libc gcc-avr
    - name: Submodules init
    - run: git submodule init
    - name: Submodules checkout
    - run: git submodule update
    - name: configure
    - run: ./bootstrap-avr
    - name: make
    - run: make
